# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: substrait_metadata.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'substrait_metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18substrait_metadata.proto\x12\"org.fsdatalab.quail_b.substrait.v1\"N\n\x10RelationMetadata\x12\x16\n\x0eschema_version\x18\x01 \x01(\r\x12\r\n\x05\x61lias\x18\x02 \x01(\t\x12\x13\n\x0btext_column\x18\x03 \x01(\t\"?\n\x10OperatorMetadata\x12\x16\n\x0eschema_version\x18\x01 \x01(\r\x12\x13\n\x0boperator_id\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'substrait_metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RELATIONMETADATA']._serialized_start=64
  _globals['_RELATIONMETADATA']._serialized_end=142
  _globals['_OPERATORMETADATA']._serialized_start=144
  _globals['_OPERATORMETADATA']._serialized_end=207
# @@protoc_insertion_point(module_scope)
